apiVersion: v1
kind: Service
metadata:
  name: mygps-mysql
  labels:
    app: mygps
spec:
  ports:
    - port: 3306
  selector:
    app: mygps
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mysqldb_gps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mygps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mygps-mysql
  labels:
    app: mygps
spec:
  selector:
    matchLabels:
      app: mygps
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mygps
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mygps-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: MYSQL_DATABASE
          value: mygpsdb
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
