apiVersion: v1
kind: Service
metadata:
  name: traccar-mysql
  labels:
    app: traccar
spec:
  ports:
    - port: 3306
  selector:
    app: traccar
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: traccar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: traccar-mysql
  labels:
    app: traccar
spec:
  selector:
    matchLabels:
      app: traccar
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traccar
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: traccar-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        command: ["/bin/bash"]
        args: ["-c", "while true; do  echo 'CREATE DATABASE traccardb;' > createdb.sql; mysql --user=root --password=$MYSQL_ROOT_PASSWORD < createdb.sql; /etc/init.d/mysql start; done"]
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
