apiVersion: v1
data:
  mysqluser: bXlzcWx1c2Vy
  password: d2VsY29tZTE=
kind: Secret
metadata:
  creationTimestamp: "2020-04-28T12:11:13Z"
  name: mysql-pass
  namespace: default
  resourceVersion: "3669"
  selfLink: /api/v1/namespaces/default/secrets/mysql-pass
  uid: 15ca3a45-3b6b-4d70-b495-c744afeb5081
type: Opaque
