apiVersion: v1
kind: Service
metadata:
  name: traccar
  namespace: gps
  labels:
    app: traccar
spec:
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    nodePort: 30082
  - name: app
    port: 5055
    targetPort: 5055
    nodePort: 30055
  selector:
    app: traccar
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gps-pv1
  namespace: gps
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /traccar/app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gps-pv-claim1
  namespace: gps
  labels:
    app: traccar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: traccar
  namespace: gps
  labels:
    app: traccar
spec:
  selector:
    matchLabels:
      app: traccar
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traccar
        tier: frontend
    spec:
      containers:
      - image: dev1983/gps:mygps
        name: traccar
        ports:
        - containerPort: 8082
          name: traccar
        volumeMounts:
        - name: traccar-persistent-storage1
          mountPath: /var/www/html
      volumes:
      - name: traccar-persistent-storage1
        persistentVolumeClaim:
          claimName: gps-pv-claim1
